CC = g++
Exercise2:
	echo "Running problem 1"
	g++ problem1.cpp -o problem1 && ./problem1
	echo "Running problem 2"
	g++ problem2.cpp -o problem2 && ./problem2
  echo "Running problem 3"
	g++ problem3.cpp -o problem3 && ./problem3
  echo "Running problem 4"
	g++ problem4.cpp -o problem4 && ./problem4
  echo "Running problem 5"
	g++ problem5.cpp -o problem5 && ./problem5
